In [ ]:
import pandas as pd

In [ ]:
# Cargar el archivo csv
df_hurtos_MDE= pd.read_csv('/content/drive/MyDrive/Dataset G659 UDEA/hurto_a_persona.csv' , sep=',')

/tmp/ipykernel_4279/493161232.py:2: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df_hurtos_MDE= pd.read_csv('/content/drive/MyDrive/Dataset G659 UDEA/hurto_a_persona.csv' , sep=',')

In [ ]:
df_hurtos_MDE

,fecha_hecho,cantidad,latitud,longitud,sexo,edad,estado_civil,grupo_actor,actividad_delictiva,parentesco,...,lugar,sede_receptora,bien,categoria_bien,grupo_bien,modelo,color,permiso,unidad_medida,fecha_ingestion
0,2017-01-01T01:00:00.000-05:00,1.0,6.299703,-75.582016,Mujer,33,Unión marital de hecho,Sin dato,Sin dato,Sin dato,...,Vía pública,Doce de Octubre,Celular,Tecnología,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
1,2017-01-01T15:00:00.000-05:00,1.0,6.250917,-75.566160,Mujer,26,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Candelaria,Celular,Tecnología,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
2,2017-01-01T14:00:00.000-05:00,1.0,6.274836,-75.554909,Hombre,30,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Aranjuez,Celular,Tecnología,Mercancía,-1,Negro,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
3,2017-01-01T16:00:00.000-05:00,1.0,6.276236,-75.553533,Hombre,37,Casado(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Aranjuez,Celular,Tecnología,Mercancía,-1,Negro,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
4,2017-01-01T16:00:00.000-05:00,1.0,6.250339,-75.586914,Hombre,87,Casado(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Laureles,Billetera,Prendas de vestir y accesorios,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326484,2023-11-30T21:30:00.000-05:00,1.0,NaN,NaN,Hombre,29,Sin dato,Sin dato,Sin dato,Sin dato,...,Vía pública,Candelaria,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326485,2023-11-30T23:00:00.000-05:00,1.0,NaN,NaN,Hombre,29,Sin dato,Sin dato,Sin dato,Sin dato,...,Vía pública,Poblado,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326486,2023-11-30T23:00:00.000-05:00,1.0,NaN,NaN,Hombre,40,Sin dato,Sin dato,Sin dato,Sin dato,...,Bar o cantina,Candelaria,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326487,2023-11-30T23:20:00.000-05:00,1.0,NaN,NaN,Hombre,29,Sin dato,Sin dato,Sin dato,Sin dato,...,Vía pública,Candelaria,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326488,2023-11-30T23:30:00.000-05:00,1.0,NaN,NaN,Mujer,26,Sin dato,Sin dato,Sin dato,Sin dato,...,Turístico,Manrique,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00

In [ ]:
df_hurtos_MDE.head()

,fecha_hecho,cantidad,latitud,longitud,sexo,edad,estado_civil,grupo_actor,actividad_delictiva,parentesco,...,lugar,sede_receptora,bien,categoria_bien,grupo_bien,modelo,color,permiso,unidad_medida,fecha_ingestion
0,2017-01-01T01:00:00.000-05:00,1.0,6.299703,-75.582016,Mujer,33,Unión marital de hecho,Sin dato,Sin dato,Sin dato,...,Vía pública,Doce de Octubre,Celular,Tecnología,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
1,2017-01-01T15:00:00.000-05:00,1.0,6.250917,-75.566160,Mujer,26,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Candelaria,Celular,Tecnología,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
2,2017-01-01T14:00:00.000-05:00,1.0,6.274836,-75.554909,Hombre,30,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Aranjuez,Celular,Tecnología,Mercancía,-1,Negro,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
3,2017-01-01T16:00:00.000-05:00,1.0,6.276236,-75.553533,Hombre,37,Casado(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Aranjuez,Celular,Tecnología,Mercancía,-1,Negro,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
4,2017-01-01T16:00:00.000-05:00,1.0,6.250339,-75.586914,Hombre,87,Casado(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Laureles,Billetera,Prendas de vestir y accesorios,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00

In [ ]:
df_hurtos_MDE.tail(10)

,fecha_hecho,cantidad,latitud,longitud,sexo,edad,estado_civil,grupo_actor,actividad_delictiva,parentesco,...,lugar,sede_receptora,bien,categoria_bien,grupo_bien,modelo,color,permiso,unidad_medida,fecha_ingestion
326479,2023-11-30T19:00:00.000-05:00,1.0,NaN,NaN,Mujer,25,Sin dato,Sin dato,Sin dato,Sin dato,...,Centro comercial,Castilla,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326480,2023-11-30T20:00:00.000-05:00,1.0,NaN,NaN,Hombre,20,Sin dato,Sin dato,Sin dato,Sin dato,...,Vía pública,Laureles,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326481,2023-11-30T20:00:00.000-05:00,1.0,NaN,NaN,Hombre,32,Sin dato,Sin dato,Sin dato,Sin dato,...,Paradero de bus,Candelaria,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326482,2023-11-30T20:45:00.000-05:00,1.0,NaN,NaN,Hombre,38,Sin dato,Sin dato,Sin dato,Sin dato,...,Vía pública,Candelaria,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326483,2023-11-30T20:58:00.000-05:00,1.0,NaN,NaN,Hombre,59,Sin dato,Sin dato,Sin dato,Sin dato,...,Vía pública,Candelaria,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326484,2023-11-30T21:30:00.000-05:00,1.0,NaN,NaN,Hombre,29,Sin dato,Sin dato,Sin dato,Sin dato,...,Vía pública,Candelaria,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326485,2023-11-30T23:00:00.000-05:00,1.0,NaN,NaN,Hombre,29,Sin dato,Sin dato,Sin dato,Sin dato,...,Vía pública,Poblado,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326486,2023-11-30T23:00:00.000-05:00,1.0,NaN,NaN,Hombre,40,Sin dato,Sin dato,Sin dato,Sin dato,...,Bar o cantina,Candelaria,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326487,2023-11-30T23:20:00.000-05:00,1.0,NaN,NaN,Hombre,29,Sin dato,Sin dato,Sin dato,Sin dato,...,Vía pública,Candelaria,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326488,2023-11-30T23:30:00.000-05:00,1.0,NaN,NaN,Mujer,26,Sin dato,Sin dato,Sin dato,Sin dato,...,Turístico,Manrique,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00

In [ ]:
df_hurtos_MDE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326489 entries, 0 to 326488
Data columns (total 36 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   fecha_hecho          326489 non-null  object
 1   cantidad             326489 non-null  float64
 2   latitud              284545 non-null  float64
 3   longitud             284545 non-null  float64
 4   sexo                 326489 non-null  object
 5   edad                 326489 non-null  int64
 6   estado_civil         326489 non-null  object
 7   grupo_actor          326489 non-null  object
 8   actividad_delictiva  326489 non-null  object
 9   parentesco           326489 non-null  object
 10  ocupacion            326489 non-null  object
 11  discapacidad         326489 non-null  object
 12  grupo_especial       326489 non-null  object
 13  medio_transporte     326489 non-null  object
 14  nivel_academico      326489 non-null  object
 15  testigo              326489 non-null  object
 16  conducta             326489 non-null  object
 17  modalidad            326489 non-null  object
 18  caracterizacion      326489 non-null  object
 19  conducta_especial    326489 non-null  object
 20  arma_medio           326489 non-null  object
 21  articulo_penal       326489 non-null  object
 22  categoria_penal      326489 non-null  object
 23  nombre_barrio        326489 non-null  object
 24  codigo_barrio        326489 non-null  object
 25  codigo_comuna        326489 non-null  object
 26  lugar                326489 non-null  object
 27  sede_receptora       326489 non-null  object
 28  bien                 326489 non-null  object
 29  categoria_bien       326489 non-null  object
 30  grupo_bien           326489 non-null  object
 31  modelo               326489 non-null  int64
 32  color                326489 non-null  object
 33  permiso              326489 non-null  object
 34  unidad_medida        326489 non-null  object
 35  fecha_ingestion      326489 non-null  object
dtypes: float64(3), int64(2), object(31)
memory usage: 89.7+ MB

In [ ]:
df_hurtos_MDE.describe()

       cantidad        latitud       longitud           edad         modelo
count  326489.0  284545.000000  284545.000000  326489.000000  326489.000000
mean        1.0       6.246950     -75.572000      34.335126       0.106527
std         0.0       0.037377       0.618576      13.120093      47.092037
min         1.0       3.855871     -76.317445      -1.000000      -1.000000
25%         1.0       6.234175     -75.587787      25.000000      -1.000000
50%         1.0       6.248980     -75.571988      32.000000      -1.000000
75%         1.0       6.259588     -75.565975      42.000000      -1.000000
max         1.0      10.155289      75.607180     121.000000    2023.000000

In [ ]:
# Visualizar que columnas tengo en mi df
df_hurtos_MDE.columns

Index(['fecha_hecho', 'cantidad', 'latitud', 'longitud', 'sexo', 'edad',
       'estado_civil', 'grupo_actor', 'actividad_delictiva', 'parentesco',
       'ocupacion', 'discapacidad', 'grupo_especial', 'medio_transporte',
       'nivel_academico', 'testigo', 'conducta', 'modalidad',
       'caracterizacion', 'conducta_especial', 'arma_medio', 'articulo_penal',
       'categoria_penal', 'nombre_barrio', 'codigo_barrio', 'codigo_comuna',
       'lugar', 'sede_receptora', 'bien', 'categoria_bien', 'grupo_bien',
       'modelo', 'color', 'permiso', 'unidad_medida', 'fecha_ingestion'],
      dtype='object')

In [ ]:
# Filtrar los registros con edad menor a 20
df_hurtos_menores_20= df_hurtos_MDE[df_hurtos_MDE['edad']<20]
df_hurtos_menores_20

,fecha_hecho,cantidad,latitud,longitud,sexo,edad,estado_civil,grupo_actor,actividad_delictiva,parentesco,...,lugar,sede_receptora,bien,categoria_bien,grupo_bien,modelo,color,permiso,unidad_medida,fecha_ingestion
23,2017-01-01T14:50:00.000-05:00,1.0,6.255573,-75.619635,Hombre,18,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,San Javier,Celular,Tecnología,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
42,2017-01-02T18:35:00.000-05:00,1.0,6.267380,-75.570119,Hombre,17,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Aranjuez,Celular,Tecnología,Mercancía,-1,Negro,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
48,2017-01-02T20:00:00.000-05:00,1.0,6.252360,-75.568387,Hombre,19,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Candelaria,Peso,"Dinero, joyas, piedras preciosas y título valor",Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
53,2017-01-02T16:30:00.000-05:00,1.0,6.214796,-75.597620,Mujer,19,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Belén,Celular,Tecnología,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
56,2017-01-02T20:00:00.000-05:00,1.0,6.252360,-75.568387,Hombre,19,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Candelaria,Celular,Tecnología,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326428,2023-11-29T08:00:00.000-05:00,1.0,NaN,NaN,Mujer,19,Sin dato,Sin dato,Sin dato,Sin dato,...,Metro Plus,Candelaria,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326457,2023-11-30T04:40:00.000-05:00,1.0,NaN,NaN,Mujer,18,Sin dato,Sin dato,Sin dato,Sin dato,...,Vía pública,Laureles,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326470,2023-11-30T12:00:00.000-05:00,1.0,NaN,NaN,Hombre,19,Sin dato,Sin dato,Sin dato,Sin dato,...,Institución de educación superior,Laureles,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326471,2023-11-30T13:04:00.000-05:00,1.0,NaN,NaN,Hombre,18,Sin dato,Sin dato,Sin dato,Sin dato,...,Vía pública,Aranjuez,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326472,2023-11-30T13:04:00.000-05:00,1.0,NaN,NaN,Hombre,18,Sin dato,Sin dato,Sin dato,Sin dato,...,Vía pública,Aranjuez,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00

In [ ]:
# Validamos los datos que tienen las columnas
pd.unique(df_hurtos_MDE.sexo)

array(['Mujer', 'Hombre', 'Sin dato'], dtype=object)

In [ ]:
pd.unique(df_hurtos_MDE.edad)

array([ 33,  26,  30,  37,  87,  29,  27,  36,  41,  59,  39,  38,  43,
        22,  20,  64,  35,  18,  28,  40,  32,  45,  23,  17,  19,  31,
        34,  25,  51,  49,  21,  47,  56,  55,  46,  48,  66,  52,  16,
        54,  24,  65,  53,  42,  44,  60,   6,  50,  62,  15,  69,  61,
        77,  63,  73,  58,  76,  14,  -1,  70,  57,  81,  71,  72,  67,
        13,  84,  68,  88,  74,  75,  90,   8,  78,  80,  10,  85,  79,
        11,   7,  89,  86,   2,  83,  82,  93,   9,  12,  91,   1,  92,
        94,  96,   4,  95,   3,   5, 121])

In [ ]:
pd.unique(df_hurtos_MDE.bien)

array(['Celular', 'Billetera', 'Elementos escolares', 'Cámara', 'Peso',
       'Cigarrillo', 'Computador', 'Cédula', 'Sin dato electrodomésticos',
       'Accesorios prendas de vestir', 'Licencia', 'Pasacintas', 'Euro',
       'Ropa exterior', 'Radio', 'Tablet', 'Salsa', 'Autopartes',
       'Sellos', 'Taladro', 'Maletín', 'Bicicleta',
       'Electrodomésticos cocina y limpieza hogar', 'Biseles',
       'Morral militar', 'Espejo', 'Factura',
       'Electrodoméstico video y audio y accesorios', 'Llave',
       'Sin dato joyas', 'Papel', 'Zapatos', 'Artículos de aseo personal',
       'Dólar', 'Pistola', 'Gato hidráulico', 'Medicamentos', 'Escritura',
       'Animales domésticos', 'Tarjeta bancaria', 'Módem', 'Encomiendas',
       'Accesorios celular', 'Sin dato documentos', 'Cargadores',
       'Elementos computador', 'Datáfono', 'Decoración del hogar', 'Soat',
       'Dvd', 'Casco moto', 'Ipod', 'Aluminio', 'Reja', 'Revólver',
       'Repuestos para maquinaria y equipo', 'Sin dato mercancías',
       'Automóvil', 'Escopeta', 'Moto', 'Campero',
       'Sin dato herramientas', 'Canguro', 'Acciones', 'Libros',
       'Sin dato maquinaria y equipo', 'Sin dato', 'Tren', 'Medidor',
       'Tarjeta de comunicación', 'Instrumento musical', 'Grabadora',
       'Carbohidratos y dulces', 'Telas', 'Pulidora', 'Beeper', 'Cheques',
       'Sin dato repuestos', 'Cd', 'Vehículo panel', 'Pila', 'Aeroplano',
       'Antenas', 'Sin dato prendas de vestir', 'Cerveza', 'Bono',
       'Máquina', 'Cdt', 'Sin dato médico', 'Carreta', 'Triciclo',
       'Elementos deportivos', 'Aguardiente', 'Sin dato licor',
       'Artículo para video', 'Sin dato materiales',
       'Promesa de compraventa', 'Accesorios de peluquería',
       'Letra de cambio', 'Máquina industrial', 'Sin dato tecnología',
       'Articulos electrónica', 'Equipos varios', 'Productos químicos',
       'Lámina', 'Proyector', 'Carne', 'Material de construcción',
       'Dijes', 'Cortadora', 'Tapas', 'Monitor', 'Silla',
       'Vallas publicitarias', 'Loterías', 'Pagaré',
       'Artículo de laboratorio', 'Bebidas', 'Juegos y muñecos',
       'Escrito', 'Pasaporte', 'Olla', 'Loción', 'Transformador',
       'Plancha de cabello', 'Sombrilla', 'Avión', 'Prendas ponal',
       'Tarjeta de identidad', 'Joyería', 'Libreta militar', 'Oro',
       'Tarjeta para computador', 'Llaveros', 'Gps', 'Planta eléctrica',
       'Moneda falsa', 'Varilla', 'Ropa interior', 'Gasolina', 'Herrajes',
       'Artículos y ropa de cama', 'Perfumería', 'Ventilador',
       'Elementos construcción hogar', 'Alicate',
       'Alimento para animales', 'Vidrios', 'Válvulas', 'Fotografías',
       'Esposas', 'Mesa', 'Contraseña cédula', 'Mobiliario del hogar',
       'Insumo médico', 'Artículos alimenticios', 'Carpa',
       'Muebles del hogar', 'Planta', 'Agenda digital', 'Placa policial',
       'Expediente', 'Motor', 'Contrato', 'Portadocumentos', 'Extintor',
       'Bolívar venezolano', 'Certificado de gases', 'Cable',
       'Cilíndros de gas', 'Amplificador de sonido', 'Secador',
       'Prendas ejercol', 'Martillo', 'Señales de tránsito',
       'Decodificadores/tarjetas decodificadoras', 'Horno',
       'Prendas cia. Vigilancia', 'Botellas', 'Arma blanca',
       'Calibre munición', 'Proveedores', 'Libra esterlina inglesa',
       'Pistola neumática', 'Escalera', 'Vitrina', 'Póliza de seguro',
       'Estuche', 'Camándulas', 'Arnés', 'Chance', 'Interior', 'Toalla',
       'Tanque', 'Carro comidas rápidas', 'Lámpara de alumbrado',
       'Productos homeopáticos', 'Revisión técnico mecánica', 'Talonario',
       'Placa', 'Carta', 'Guantes', 'Botas de caucho', 'Caneca', 'Boleta',
       'Palma', 'Etiquetas', 'Marquillas', 'Aparato médico',
       'Acero inoxidable', 'Paquete de software', 'Whiskey', 'Limadura',
       'Megáfono', 'Documentación electoral', 'Registro civil',
       'Cuenta de ahorro', 'Caja desbloqueo celulares', 'Bota militar',
       'Permiso porte de arma', 'Visa', 'Sumadora', 'Cuchillo',
       'Linterna', 'Forro para electrodoméstico',
       'Sin dato títulos valor', 'Carátula', 'Frutas y verduras',
       'Subametralladora', 'Diario digital', 'Aspiradora',
       'Instrumento óptico', 'Lácteos', 'Ladrillo', 'Sin dato munición',
       'Chocolate', 'Motobombas', 'Conservas', 'Películas',
       'Sin dato mobiliario del hogar', 'Sin dato dinero',
       'Elementos de la cocina', 'Mangueras', 'Piedra preciosa',
       'Sin dato armas', 'Atornillador', 'Analgésico', 'Plancha',
       'Escarapela', 'Glucosa', 'Teléfono satelital', 'Cortopunzantes',
       'Sin dato transporte agua', 'Acid-mantle', 'Torres de energía',
       'Caja fuerte', 'Patente', 'Venado', 'Real brasilero',
       'Ave salvaje', 'Pintura', 'Vcd', 'Taller automotor', 'Adaptador',
       'Reata militar', 'Cinturón', 'Fuentes luminosas', 'Registradora',
       'Sin dato articulos electrónica', 'Sin dato autopartes',
       'Sin dato materia prima', 'Contador', 'Aceite', 'Pipeta',
       'Quemador cd', 'Conmutador', 'Tubo', 'Tubería', 'Camioneta',
       'Microbus', 'Medicamento trastorno ansiedad y mental', 'Ron',
       'Hierro', 'Fotocopiadora', 'Alambre', 'Huevos', 'Cobre',
       'Alimentos enlatados y embutidos', 'Basuco', 'Madera',
       'Documentos falsos', 'Esculturas', 'Sector residencial', 'Vino',
       'Chaleco antibala', 'Taco', 'Champaña', 'Leche', 'Supermercado',
       'Casa', 'Accesorios armas', 'Ataud', 'Preservativos/condones',
       'Broca', 'Hilos industriales', 'Tejas', 'Bomba eléctrica',
       'Micrófono', 'Lingotes de oro', 'Abono', 'Planos', 'Teatro',
       'Trailer', 'Cemento', 'Consola', 'Telex', 'Balanza',
       'Vibrocompactador', 'Peluquería', 'Cuerda', 'Prensa', 'Joyero',
       'Carabina', 'Canastillas', 'Balón de fútbol', 'Maniquí',
       'Rollo de cinta', 'Báscula', 'Mallas estacionarias', 'Tequila',
       'Bolsa plástica', 'Juguete arma bélica', 'Máster', 'Cerámicas',
       'Material de intendencia', 'Aceite de cocina', 'Candado',
       'Patineta', 'Tabaco', 'Ave de jaula o pequeña', 'Camión',
       'Cabello', 'Binoculares', 'Paramotor', 'Pala', 'Interruptor',
       'Aperitivo', 'Cinta', 'Volantes', 'Arena', 'Lector', 'Cartucho',
       'Andamio', 'Coche para bebe', 'Aceite de motor',
       'Pistola de paint ball', 'Archivador', 'Peineta', 'Termos',
       'Envase', 'Calcio', 'Radiomódem', 'Manual', 'Alcohol (químico)',
       'Remachadora', 'Bombas', 'Medicamento antiinflamatorio',
       'Obra musical', 'Línea telefónica', 'Fresas', 'Caladora compacta',
       'Batidora', 'Ups', 'Regulador de gas', 'Vitamina', 'Fulminantes',
       'Plata', 'Grúa', 'Algodón', 'Líquido limpiador', 'Pvc',
       'Otros animales', 'Tintas para litografía', 'Gel', 'Helicóptero',
       'Sin dato combustibles', 'Rollo de plástico', 'Sustancia reactiva',
       'Cartón', 'Medicamento trastorno estomacal', 'Alcohol', 'Rejilla',
       'Ginebra', 'Machete', 'Vainilla', 'Cronómetro', 'Zorro',
       'Estampillas', 'Veneno', 'Vodka', 'Suelas', 'Barra',
       'Lámpara secadora', 'Fusil', 'Ametralladora', 'Piscinas inflables',
       'Cocaína', 'Prendedor', 'Masajeador', 'Platinas férreos',
       'Consultorio médico', 'Serrucho', 'Tapa contador agua',
       'Solución salina', 'Anillos plásticos', 'Suero oral',
       'Escopolamina', 'Caja de paso', 'Elemento químico',
       'Letra de ahorro', 'Divisiones', 'Granada', 'Toma', 'Lote',
       'Vacuna', 'Discos para pulidora', 'Tortuga', 'Sucre ecuatoriano',
       'Bus', 'Cantimplora', 'Sabajón', 'Perdigones recargar cartuchos',
       'Bombilla recargable', 'Armadillo', 'Vehículo tracción animal',
       'Guadua', 'Botones', 'Tapa de alcantarilla', 'Selladora', 'Cacao',
       'Ácido'], dtype=object)

In [ ]:
df_hurtos_MDE[df_hurtos_MDE['bien']=="Cemento"]

,fecha_hecho,cantidad,latitud,longitud,sexo,edad,estado_civil,grupo_actor,actividad_delictiva,parentesco,...,lugar,sede_receptora,bien,categoria_bien,grupo_bien,modelo,color,permiso,unidad_medida,fecha_ingestion
59608,2009-10-08T14:45:00.000-05:00,1.0,6.258541,-75.598799,Hombre,24,Soltero(a),Sin dato,Sin dato,Sin dato,...,Obra en construcción,Laureles,Cemento,Materiales y elementos para la construcción,Mercancía,-1,Gris,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
59617,2009-10-08T14:45:00.000-05:00,1.0,6.258541,-75.598799,Hombre,24,Soltero(a),Sin dato,Sin dato,Sin dato,...,Obra en construcción,Laureles,Cemento,Materiales y elementos para la construcción,Mercancía,-1,Gris,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
76448,2014-01-03T13:30:00.000-05:00,1.0,6.246881,-75.582795,Hombre,48,Casado(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Laureles,Cemento,Materiales y elementos para la construcción,Mercancía,-1,Gris,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
94293,2015-11-01T00:00:00.000-05:00,1.0,6.283312,-75.561630,Mujer,65,Casado(a),Sin dato,Sin dato,Sin dato,...,Residencia,Aranjuez,Cemento,Materiales y elementos para la construcción,Mercancía,-1,Gris,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
98429,2016-03-01T11:00:00.000-05:00,1.0,6.265134,-75.542346,Hombre,46,Casado(a),Sin dato,Sin dato,Sin dato,...,Obra en construcción,Manrique,Cemento,Materiales y elementos para la construcción,Mercancía,-1,Café,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
108322,2016-09-24T09:00:00.000-05:00,1.0,6.305808,-75.569125,Mujer,38,Soltero(a),Sin dato,Sin dato,Sin dato,...,"Hotel, motel y hostal",Castilla,Cemento,Materiales y elementos para la construcción,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
111042,2016-11-08T13:00:00.000-05:00,1.0,6.264576,-75.543269,Mujer,82,Soltero(a),Sin dato,Sin dato,Sin dato,...,Residencia,Manrique,Cemento,Materiales y elementos para la construcción,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
177347,2020-09-07T10:00:00.000-05:00,1.0,6.228036,-75.530481,Mujer,61,Soltero(a),Sin dato,Sin dato,Sin dato,...,Casa o apartamento,Buenos Aires,Cemento,Materiales y elementos para la construcción,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00

In [ ]:
df_hurtos_MDE[df_hurtos_MDE['bien']=="Maniquí" ]

,fecha_hecho,cantidad,latitud,longitud,sexo,edad,estado_civil,grupo_actor,actividad_delictiva,parentesco,...,lugar,sede_receptora,bien,categoria_bien,grupo_bien,modelo,color,permiso,unidad_medida,fecha_ingestion
69060,2012-07-09T00:00:00.000-05:00,1.0,6.291109,-75.571958,Mujer,31,Soltero(a),Sin dato,Sin dato,Sin dato,...,"Sede social, club, auditorio o similar",Castilla,Maniquí,Otros elementos,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00

In [ ]:
df_hurtos_MDE[df_hurtos_MDE['bien']=="Lingotes de oro"]

,fecha_hecho,cantidad,latitud,longitud,sexo,edad,estado_civil,grupo_actor,actividad_delictiva,parentesco,...,lugar,sede_receptora,bien,categoria_bien,grupo_bien,modelo,color,permiso,unidad_medida,fecha_ingestion
56127,2017-12-16T17:10:00.000-05:00,1.0,6.226030,-75.591268,Hombre,29,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Belén,Lingotes de oro,Materia prima,Mercancía,-1,Oro,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
235937,2021-05-16T18:00:00.000-05:00,1.0,6.235752,-75.555670,Mujer,28,Casado(a),Sin dato,Sin dato,Sin dato,...,Cajero electrónico,Buenos Aires,Lingotes de oro,Materia prima,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
268237,2022-03-17T01:30:00.000-05:00,1.0,6.286598,-75.556031,Hombre,22,Soltero(a),Sin dato,Sin dato,Sin dato,...,Cajero electrónico,Aranjuez,Lingotes de oro,Materia prima,Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00

In [ ]:
pd.unique(df_hurtos_MDE.nombre_barrio)

array(['Doce de Octubre No.2', 'La Candelaria', 'Campo Valdés No.1',
       'Naranjal', 'La Loma de los Bernal', 'Volcana Guayabal',
       'Manrique Central No.1', 'Barrio Caycedo', 'Boston',
       'Los Cerros el Vergel', 'Bermejal-Los Alamos', 'El Diamante',
       'Sevilla', 'Campo Valdés No.2', 'San Pedro', 'San Javier No.1',
       'Prado', 'La Aguacatala', 'Santa Fé', 'San Lucas', 'El Pinal',
       'Suramericana', 'Villa Nueva', 'Terminal de Transporte',
       'San Benito', 'Granada', 'La Palma', 'Parque Norte',
       'Universidad de Antioquia', 'La Mota', 'La Francia',
       'Jesús Nazareno', 'Palenque', 'Cataluña', 'La Florida', 'Loreto',
       'Barrio Colón', 'Castilla', 'Caribe', 'Plaza de Ferias',
       'Pedregal', 'Tricentenario', 'La Gloria', 'La Milagrosa',
       'Cristo Rey', 'Boyacá', 'U.D. Atanasio Girardot', 'Villa Carlota',
       'Guayaquil', 'Gerona', 'Brasilia', 'El Tesoro', 'Laureles',
       'Los Conquistadores', 'Ecoparque Cerro El Volador', 'Belén',
       'Doce de Octubre No.1', 'Robledo', 'La Castellana', 'Bomboná No.1',
       'Rosales', 'San Martín de Porres', 'Los Alpes', 'Trinidad',
       'Los Alcázares', 'El Salvador', 'Manila', 'Estación Villa',
       'Córdoba', 'El Poblado', 'Miranda', 'Astorga', 'Los Naranjos',
       'El Velódromo', 'Aures No.2', 'Bolivariana', 'San Diego',
       'Barrio Colombia', 'Kennedy', 'Simón Bolívar', 'La Floresta',
       'Las Playas', 'Las Lomas No.1', 'Aures No.1', 'Perpetuo Socorro',
       'El Corazón', 'Florencia', 'El Chagualo', 'Miraflores',
       'Media Luna', 'Cerro Nutibara Ins.',
       'Área Urbana Cgto. San Antonio de Prado', 'Guayabal',
       'Las Violetas', 'Lorena', 'Patio Bonito', 'López de Mesa',
       'Alejandría', 'Pajarito S.C.', 'Estadio', 'Piedra Gorda',
       'Manrique Central No.2', 'Aranjuez', 'Lalinde', 'San Javier No.2',
       'Área de expansión Belén', 'La Libertad', 'Los Balsos No.2',
       'Picacho', 'Florida Nueva', 'Carlos E. Restrepo', 'Altamira',
       'Versalles No.1', 'Asomadera No.1', 'Pajarito', 'Calle Nueva',
       'Fátima', 'Villa Flora', 'Campo Amor', 'La Alpujarra', 'Oleoducto',
       'Santa María de los Ángeles', 'La Colina', 'San Miguel',
       'Pablo VI', 'El Rodeo', 'Universidad Nacional', 'San Joaquín',
       'Mirador del Doce', 'Héctor Abad Gómez',
       'Área de expansión Pajarito', 'Las Acacias', 'Moscú No.1',
       'Centro Administrativo', 'Altavista', 'La Pilarica', 'Tejelo',
       'Las Granjas', 'Cucaracho', 'Popular', 'La Loma',
       'Corazón de Jesús', 'Los Ángeles', 'Girardot', 'San Bernardo',
       'San Germán', 'Tenche', 'Villa Hermosa', 'El Danubio',
       'Facultad de Minas U. Nal', 'Progreso', 'La Salle', 'Calasanz',
       'Buenos Aires', 'Parque Juan Pablo II', 'Santo Domingo Savio No.2',
       'Juan XXIIIi la Quiebra', 'El Rincón', 'Alejandro Echavarría',
       'El Raizal', 'Área Urbana Cgto. San Cristóbal', 'Veinte de Julio',
       'El Pomar', 'La América', 'Cementerio Universal',
       'Manrique Oriental', 'Santa Elena sector central',
       'El Nogal-Los Almendros', 'Francisco Antonio Zea', 'La Pradera',
       'Santa Lucía', 'Alfonso López', 'La Esperanza', 'La Mansión',
       'Los Balsos No.1', 'Las Lomas No.2', 'Berlin',
       'B. Cerro el Volador', 'Los Colores', 'Campo Alegre', 'Santa Inés',
       'Miravalle', 'La Frontera', 'Santa Mónica', 'Jardín Botánico',
       'Facultad de Minas U. Nacional', 'Granizal', 'Cuarta Brigada',
       'Nueva Villa del Aburrá', 'Santa Teresita', 'Sucre', 'Las Brisas',
       'Palermo', 'Sin dato', 'Boqueron', 'Bello Horizonte', 'Toscana',
       'Villa Guadalupe', 'Santa Cruz', 'Ferrini', 'Los Pinos',
       'Antonio Nariño', 'La Piñuela', 'La Ladera', 'Diego Echavarría',
       'Castropol', 'Santa Margarita', 'Enciso', 'Los Mangos',
       'Las Mercedes', 'Las Palmas', 'Barrio Cristóbal', 'Bomboná No.2',
       'Belencito', 'Moravia', 'Belalcázar', 'Las Estancias',
       'Playón de los Comuneros', 'U.P.B', 'San Isidro',
       'Bosques de San Pablo', 'Asomadera No.2', 'San José la Cima No.2',
       'Ocho de Marzo', 'San Antonio', 'Villatina', 'La Rosa',
       'Santander', 'Andalucía', 'Cerro Nutibara', 'San Pablo',
       'El Corazon el Morro', 'El Plan', 'Villa del Socorro', 'La Isla',
       'Las Playas S.C.', 'Calasania Parte Alta', 'Barrios de Jesús',
       'Altos del Poblado', 'Hospital San Vicente de Paúl',
       'Fuente Clara', 'Santo Domingo Savio No.1', 'Pedregal Alto',
       'La Avanzada', 'Blanquizal', 'Las Esmeraldas', 'Las Palmas S.E.',
       'Nueva Villa de la Iguaná', 'San Pablo A.V.',
       'María Cano-Carambolas', 'Olaya Herrera', 'La Hondonada',
       'Juan Pablo II', 'El Castillo', 'Área de expansión Altavista',
       'El Diamante No.2', 'Batallón Girardot',
       'Área de expansión San Antonio De Prado', 'Las Independencias',
       'Moscú No.2', 'Aldea Pablo VI', 'Naranjal S.C.', 'Llanaditas',
       'Picachito', 'Progreso No.2', 'El Socorro', 'Villa Niza',
       'Nuevos Conquistadores', 'San Jose', 'Monteclaro',
       'Área de expansión Calasanz', 'La Verde', 'Carpinelo',
       'Fac. Veterinaria y Zootecnia U.De.A.', 'Metropolitano',
       'Eduardo Santos', 'La Cuchilla', 'Villa Lilliam',
       'La Esperanza No.2', 'San Jose del Manzanillo',
       'San José la Cima No.1', 'Potrerito', 'Trece de Noviembre',
       'Piedras Blancas Matasano', 'Montanita', 'Mazo', 'El Pesebre',
       'El Llano Santa Elena', 'El Salado', 'El Picacho', 'La Cruz',
       'Betania', 'Travesias', 'Santa Rosa de Lima', 'La Sierra',
       'Batallón Cuarta Brigada', 'El Yolombo', 'El Jardin', 'El Carmelo',
       'El Placer', 'Oriente', 'Altavista Sector Central',
       'El Compromiso', 'Sin dato 80 San Antonio de Prado', 'El Llano',
       'Sin dato 90 Santa Elena', 'El Cerro', 'Villa Turbay',
       'Versalles No.2', 'La Palma S.C.', 'Yarumalito', 'Barro Blanco',
       'Aguas Frias', 'Sin dato 10 La Candelaria', 'El Triunfo',
       'Asomadera No.3', 'El Astillero', 'El Uvito', 'La Esperanza A.V.',
       'San Jose de La Montaña', 'La Ilusion', 'La Florida S.A.P.',
       'Palmitas sector central', 'V. El Salado', 'La Aldea',
       'La Frisola', 'Sin dato 60 San Cristobal', 'Buga Patio Bonito',
       'La Sucia', 'El Patio', 'Potrera Miserenga', 'Urquita', 'La Suiza',
       'Área de expansión Eduardo Santos', 'Área de expansión El Noral',
       'Sin dato 9 Buenos Aires', 'Sin dato 16 Belen',
       'Sin dato 13 San Javier', 'Sin dato 14 El Poblado',
       'Sin dato 3 Manrique', 'Sin dato 7 Robledo',
       'Sin dato 15 Guayabal', 'Sin dato 6 Doce de Octubre',
       'Sin dato 11 Laureles -  Estadio'], dtype=object)

In [ ]:
df_hurtos_udea=df_hurtos_MDE[df_hurtos_MDE['nombre_barrio']=='Universidad de Antioquia']
df_hurtos_udea

,fecha_hecho,cantidad,latitud,longitud,sexo,edad,estado_civil,grupo_actor,actividad_delictiva,parentesco,...,lugar,sede_receptora,bien,categoria_bien,grupo_bien,modelo,color,permiso,unidad_medida,fecha_ingestion
42,2017-01-02T18:35:00.000-05:00,1.0,6.267380,-75.570119,Hombre,17,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Aranjuez,Celular,Tecnología,Mercancía,-1,Negro,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
230,2017-01-06T00:00:00.000-05:00,1.0,6.267134,-75.571265,Hombre,31,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Aranjuez,Peso,"Dinero, joyas, piedras preciosas y título valor",Mercancía,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
231,2017-01-06T00:00:00.000-05:00,1.0,6.267134,-75.571265,Hombre,31,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Aranjuez,Celular,Tecnología,Mercancía,-1,Negro,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
7227,2017-02-05T13:00:00.000-05:00,1.0,6.267345,-75.566883,Hombre,49,Soltero(a),Sin dato,Sin dato,Sin dato,...,Institución de educación superior,Aranjuez,Bicicleta,Vehículos de 2 o 4 ruedas,Vehículo,-1,Negro,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
7577,2017-02-11T12:30:00.000-05:00,1.0,6.264601,-75.567645,Hombre,31,Unión marital de hecho,Sin dato,Sin dato,Sin dato,...,Vía pública,Aranjuez,Celular,Tecnología,Mercancía,-1,Negro,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322014,2023-09-26T03:00:00.000-05:00,1.0,NaN,NaN,Hombre,31,Sin dato,Sin dato,Sin dato,Sin dato,...,Centro comercial,La Estrella,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
322887,2023-10-06T19:00:00.000-05:00,1.0,NaN,NaN,Hombre,42,Sin dato,Sin dato,Sin dato,Sin dato,...,Estación del Metro plus,Aranjuez,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
324664,2023-10-30T17:00:00.000-05:00,1.0,NaN,NaN,Hombre,34,Sin dato,Sin dato,Sin dato,Sin dato,...,Institución de educación superior,Candelaria,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
325256,2023-11-05T20:30:00.000-05:00,1.0,NaN,NaN,Hombre,36,Sin dato,Sin dato,Sin dato,Sin dato,...,Bus de servicio público,Laureles,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00
326286,2023-11-25T10:00:00.000-05:00,1.0,NaN,NaN,Hombre,48,Sin dato,Sin dato,Sin dato,Sin dato,...,Hospital o centro de salud,Aranjuez,Sin dato,Sin dato,Sin dato,-1,Sin dato,Sin dato,Sin dato,2024-10-06T04:07:03.000-05:00

In [ ]:
# Calcular promedio de edad de los hurtos cometidos en Udea
round(df_hurtos_udea.edad.mean(), 2)

np.float64(29.1)

In [ ]:
# Calcular la desviacion estandar de los hurtos cometidos en Udea
round(df_hurtos_udea.edad.std(),2)

10.98

In [ ]:
df_hurtos_udea.describe()

       cantidad      latitud     longitud         edad  modelo
count    1291.0  1211.000000  1211.000000  1291.000000  1291.0
mean        1.0     6.265608   -75.568972    29.103796    -1.0
std         0.0     0.001290     0.001433    10.976440     0.0
min         1.0     6.264453   -75.572081    -1.000000    -1.0
25%         1.0     6.264779   -75.569765    21.000000    -1.0
50%         1.0     6.265122   -75.568984    26.000000    -1.0
75%         1.0     6.265721   -75.567635    34.000000    -1.0
max         1.0     6.270530   -75.566309    73.000000    -1.0

In [ ]:
pd.unique(df_hurtos_MDE.actividad_delictiva)

array(['Sin dato'], dtype=object)

In [ ]:
pd.unique(df_hurtos_MDE.modelo)

array([  -1, 1980, 1996, 1998, 1990, 1984, 2004, 2000, 1997, 1989, 1999,
       1995, 1979, 1991, 1977, 1982, 1994, 2006, 2007, 2003, 1993, 2002,
       2008, 2009, 2010, 2001, 2013, 2011, 2014, 2015, 2005, 2012, 2019,
       2017, 2018, 2020,    0, 2022, 2023, 2016, 1950, 2021])

# **Limpieza de datos**

In [ ]:
df_hurtos_MDE.isnull().sum()

fecha_hecho                0
cantidad                   0
latitud                41944
longitud               41944
sexo                       0
edad                       0
estado_civil               0
grupo_actor                0
actividad_delictiva        0
parentesco                 0
ocupacion                  0
discapacidad               0
grupo_especial             0
medio_transporte           0
nivel_academico            0
testigo                    0
conducta                   0
modalidad                  0
caracterizacion            0
conducta_especial          0
arma_medio                 0
articulo_penal             0
categoria_penal            0
nombre_barrio              0
codigo_barrio              0
codigo_comuna              0
lugar                      0
sede_receptora             0
bien                       0
categoria_bien             0
grupo_bien                 0
modelo                     0
color                      0
permiso                    0
unidad_medida              0
fecha_ingestion            0
dtype: int64

In [ ]:
# Eliminar las columnas
df_hurtos_MDE.drop(columns=['latitud', 'longitud', 'modelo'], inplace=True)

In [ ]:
df_hurtos_MDE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326489 entries, 0 to 326488
Data columns (total 33 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   fecha_hecho          326489 non-null  object
 1   cantidad             326489 non-null  float64
 2   sexo                 326489 non-null  object
 3   edad                 326489 non-null  int64
 4   estado_civil         326489 non-null  object
 5   grupo_actor          326489 non-null  object
 6   actividad_delictiva  326489 non-null  object
 7   parentesco           326489 non-null  object
 8   ocupacion            326489 non-null  object
 9   discapacidad         326489 non-null  object
 10  grupo_especial       326489 non-null  object
 11  medio_transporte     326489 non-null  object
 12  nivel_academico      326489 non-null  object
 13  testigo              326489 non-null  object
 14  conducta             326489 non-null  object
 15  modalidad            326489 non-null  object
 16  caracterizacion      326489 non-null  object
 17  conducta_especial    326489 non-null  object
 18  arma_medio           326489 non-null  object
 19  articulo_penal       326489 non-null  object
 20  categoria_penal      326489 non-null  object
 21  nombre_barrio        326489 non-null  object
 22  codigo_barrio        326489 non-null  object
 23  codigo_comuna        326489 non-null  object
 24  lugar                326489 non-null  object
 25  sede_receptora       326489 non-null  object
 26  bien                 326489 non-null  object
 27  categoria_bien       326489 non-null  object
 28  grupo_bien           326489 non-null  object
 29  color                326489 non-null  object
 30  permiso              326489 non-null  object
 31  unidad_medida        326489 non-null  object
 32  fecha_ingestion      326489 non-null  object
dtypes: float64(1), int64(1), object(31)
memory usage: 82.2+ MB

In [ ]:
# Ordenar de manera ascendente los nombres de los barrios
pd.unique(df_hurtos_MDE.nombre_barrio.sort_values(ascending=True))

array(['Aguas Frias', 'Aldea Pablo VI', 'Alejandro Echavarría',
       'Alejandría', 'Alfonso López', 'Altamira', 'Altavista',
       'Altavista Sector Central', 'Altos del Poblado', 'Andalucía',
       'Antonio Nariño', 'Aranjuez', 'Asomadera No.1', 'Asomadera No.2',
       'Asomadera No.3', 'Astorga', 'Aures No.1', 'Aures No.2',
       'B. Cerro el Volador', 'Barrio Caycedo', 'Barrio Colombia',
       'Barrio Colón', 'Barrio Cristóbal', 'Barrios de Jesús',
       'Barro Blanco', 'Batallón Girardot', 'Belalcázar', 'Belencito',
       'Bello Horizonte', 'Belén', 'Berlin', 'Bermejal-Los Alamos',
       'Betania', 'Blanquizal', 'Bolivariana', 'Bomboná No.1',
       'Bomboná No.2', 'Boqueron', 'Bosques de San Pablo', 'Boston',
       'Boyacá', 'Brasilia', 'Buenos Aires', 'Buga Patio Bonito',
       'Calasania Parte Alta', 'Calasanz', 'Calle Nueva', 'Campo Alegre',
       'Campo Amor', 'Campo Valdés No.1', 'Campo Valdés No.2', 'Caribe',
       'Carlos E. Restrepo', 'Carpinelo', 'Castilla', 'Castropol',
       'Cataluña', 'Cementerio Universal', 'Centro Administrativo',
       'Cerro Nutibara', 'Corazón de Jesús', 'Cristo Rey',
       'Cuarta Brigada', 'Cucaracho', 'Córdoba', 'Diego Echavarría',
       'Doce de Octubre No.1', 'Doce de Octubre No.2',
       'Ecoparque Cerro El Volador', 'Eduardo Santos', 'El Astillero',
       'El Carmelo', 'El Castillo', 'El Cerro', 'El Chagualo',
       'El Compromiso', 'El Corazon el Morro', 'El Corazón', 'El Danubio',
       'El Diamante', 'El Diamante No.2', 'El Jardin', 'El Llano',
       'El Llano Santa Elena', 'El Nogal-Los Almendros', 'El Patio',
       'El Pesebre', 'El Picacho', 'El Pinal', 'El Placer', 'El Plan',
       'El Poblado', 'El Pomar', 'El Raizal', 'El Rincón', 'El Rodeo',
       'El Salado', 'El Salvador', 'El Socorro', 'El Tesoro',
       'El Triunfo', 'El Uvito', 'El Velódromo', 'El Yolombo', 'Enciso',
       'Estación Villa', 'Estadio',
       'Fac. Veterinaria y Zootecnia U.De.A.',
       'Facultad de Minas U. Nacional', 'Ferrini', 'Florencia',
       'Florida Nueva', 'Francisco Antonio Zea', 'Fuente Clara', 'Fátima',
       'Gerona', 'Girardot', 'Granada', 'Granizal', 'Guayabal',
       'Guayaquil', 'Hospital San Vicente de Paúl', 'Héctor Abad Gómez',
       'Jardín Botánico', 'Jesús Nazareno', 'Juan Pablo II',
       'Juan XXIIIi la Quiebra', 'Kennedy', 'La Aguacatala', 'La Aldea',
       'La Alpujarra', 'La América', 'La Avanzada', 'La Candelaria',
       'La Castellana', 'La Colina', 'La Cruz', 'La Cuchilla',
       'La Esperanza', 'La Esperanza No.2', 'La Floresta', 'La Florida',
       'La Francia', 'La Frisola', 'La Frontera', 'La Gloria',
       'La Hondonada', 'La Ilusion', 'La Isla', 'La Ladera',
       'La Libertad', 'La Loma', 'La Loma de los Bernal', 'La Mansión',
       'La Milagrosa', 'La Mota', 'La Palma', 'La Pilarica', 'La Piñuela',
       'La Pradera', 'La Rosa', 'La Salle', 'La Sierra', 'La Sucia',
       'La Suiza', 'La Verde', 'Lalinde', 'Las Acacias', 'Las Brisas',
       'Las Esmeraldas', 'Las Estancias', 'Las Granjas',
       'Las Independencias', 'Las Lomas No.1', 'Las Lomas No.2',
       'Las Mercedes', 'Las Palmas', 'Las Playas', 'Las Violetas',
       'Laureles', 'Llanaditas', 'Lorena', 'Loreto', 'Los Alcázares',
       'Los Alpes', 'Los Balsos No.1', 'Los Balsos No.2',
       'Los Cerros el Vergel', 'Los Colores', 'Los Conquistadores',
       'Los Mangos', 'Los Naranjos', 'Los Pinos', 'Los Ángeles',
       'López de Mesa', 'Manila', 'Manrique Central No.1',
       'Manrique Central No.2', 'Manrique Oriental',
       'María Cano-Carambolas', 'Mazo', 'Media Luna', 'Metropolitano',
       'Mirador del Doce', 'Miraflores', 'Miranda', 'Miravalle',
       'Montanita', 'Monteclaro', 'Moravia', 'Moscú No.1', 'Moscú No.2',
       'Naranjal', 'Nueva Villa de la Iguaná', 'Nueva Villa del Aburrá',
       'Nuevos Conquistadores', 'Ocho de Marzo', 'Olaya Herrera',
       'Oleoducto', 'Oriente', 'Pablo VI', 'Pajarito', 'Palenque',
       'Palermo', 'Palmitas sector central', 'Parque Juan Pablo II',
       'Parque Norte', 'Patio Bonito', 'Pedregal', 'Pedregal Alto',
       'Perpetuo Socorro', 'Picachito', 'Picacho', 'Piedra Gorda',
       'Piedras Blancas Matasano', 'Playón de los Comuneros',
       'Plaza de Ferias', 'Popular', 'Potrera Miserenga', 'Potrerito',
       'Prado', 'Progreso', 'Progreso No.2', 'Robledo', 'Rosales',
       'San Antonio', 'San Benito', 'San Bernardo', 'San Diego',
       'San Germán', 'San Isidro', 'San Javier No.1', 'San Javier No.2',
       'San Joaquín', 'San Jose', 'San Jose de La Montaña',
       'San Jose del Manzanillo', 'San José la Cima No.1',
       'San José la Cima No.2', 'San Lucas', 'San Martín de Porres',
       'San Miguel', 'San Pablo', 'San Pedro', 'Santa Cruz',
       'Santa Elena sector central', 'Santa Fé', 'Santa Inés',
       'Santa Lucía', 'Santa Margarita', 'Santa María de los Ángeles',
       'Santa Mónica', 'Santa Rosa de Lima', 'Santa Teresita',
       'Santander', 'Santo Domingo Savio No.1',
       'Santo Domingo Savio No.2', 'Sevilla', 'Simón Bolívar', 'Sin dato',
       'Sin dato 10 La Candelaria', 'Sin dato 11 Laureles -  Estadio',
       'Sin dato 13 San Javier', 'Sin dato 14 El Poblado',
       'Sin dato 15 Guayabal', 'Sin dato 16 Belen', 'Sin dato 3 Manrique',
       'Sin dato 6 Doce de Octubre', 'Sin dato 60 San Cristobal',
       'Sin dato 7 Robledo', 'Sin dato 80 San Antonio de Prado',
       'Sin dato 9 Buenos Aires', 'Sin dato 90 Santa Elena', 'Sucre',
       'Suramericana', 'Tejelo', 'Tenche', 'Terminal de Transporte',
       'Toscana', 'Travesias', 'Trece de Noviembre', 'Tricentenario',
       'Trinidad', 'U.P.B', 'Universidad Nacional',
       'Universidad de Antioquia', 'Urquita', 'V. El Salado',
       'Veinte de Julio', 'Versalles No.1', 'Versalles No.2',
       'Villa Carlota', 'Villa Flora', 'Villa Guadalupe', 'Villa Hermosa',
       'Villa Lilliam', 'Villa Niza', 'Villa Nueva', 'Villa Turbay',
       'Villa del Socorro', 'Villatina', 'Volcana Guayabal', 'Yarumalito',
       'Área Urbana Cgto. San Antonio de Prado',
       'Área Urbana Cgto. San Cristóbal', 'Área de expansión Altavista',
       'Área de expansión Belén', 'Área de expansión Calasanz',
       'Área de expansión Eduardo Santos', 'Área de expansión El Noral',
       'Área de expansión Pajarito',
       'Área de expansión San Antonio De Prado'], dtype=object)

In [ ]:
# Renombrar los registros
df_hurtos_MDE.nombre_barrio.replace(
     { "U.D. Atanasio Girardot":"Estadio",
       "La Palma S.C.":"La Palma",
       "Naranjal S.C.":"Naranjal",
       "San Pablo A.V.":"San Pablo",
       "Las Palmas S.E.":"Las Palmas",
       "Las Playas S.C.":"Las Playas",
       "La Florida S.A.P.":"La Florida",
       "La Esperanza A.V.":"La Esperanza",
       "Facultad de Minas U. Nal":"Facultad de Minas U. Nacional",
       "Pajarito S.C.":"Pajarito",
       "Cerro Nutibara Ins.":"Cerro Nutibara",
       "Batallón Cuarta Brigada":"Cuarta Brigada"}, inplace=True)

In [ ]:
# Verificamos los registros en barrio
pd.unique(df_hurtos_MDE.nombre_barrio)

array(['Doce de Octubre No.2', 'La Candelaria', 'Campo Valdés No.1',
       'Naranjal', 'La Loma de los Bernal', 'Volcana Guayabal',
       'Manrique Central No.1', 'Barrio Caycedo', 'Boston',
       'Los Cerros el Vergel', 'Bermejal-Los Alamos', 'El Diamante',
       'Sevilla', 'Campo Valdés No.2', 'San Pedro', 'San Javier No.1',
       'Prado', 'La Aguacatala', 'Santa Fé', 'San Lucas', 'El Pinal',
       'Suramericana', 'Villa Nueva', 'Terminal de Transporte',
       'San Benito', 'Granada', 'La Palma', 'Parque Norte',
       'Universidad de Antioquia', 'La Mota', 'La Francia',
       'Jesús Nazareno', 'Palenque', 'Cataluña', 'La Florida', 'Loreto',
       'Barrio Colón', 'Castilla', 'Caribe', 'Plaza de Ferias',
       'Pedregal', 'Tricentenario', 'La Gloria', 'La Milagrosa',
       'Cristo Rey', 'Boyacá', 'Estadio', 'Villa Carlota', 'Guayaquil',
       'Gerona', 'Brasilia', 'El Tesoro', 'Laureles',
       'Los Conquistadores', 'Ecoparque Cerro El Volador', 'Belén',
       'Doce de Octubre No.1', 'Robledo', 'La Castellana', 'Bomboná No.1',
       'Rosales', 'San Martín de Porres', 'Los Alpes', 'Trinidad',
       'Los Alcázares', 'El Salvador', 'Manila', 'Estación Villa',
       'Córdoba', 'El Poblado', 'Miranda', 'Astorga', 'Los Naranjos',
       'El Velódromo', 'Aures No.2', 'Bolivariana', 'San Diego',
       'Barrio Colombia', 'Kennedy', 'Simón Bolívar', 'La Floresta',
       'Las Playas', 'Las Lomas No.1', 'Aures No.1', 'Perpetuo Socorro',
       'El Corazón', 'Florencia', 'El Chagualo', 'Miraflores',
       'Media Luna', 'Cerro Nutibara',
       'Área Urbana Cgto. San Antonio de Prado', 'Guayabal',
       'Las Violetas', 'Lorena', 'Patio Bonito', 'López de Mesa',
       'Alejandría', 'Pajarito', 'Piedra Gorda', 'Manrique Central No.2',
       'Aranjuez', 'Lalinde', 'San Javier No.2',
       'Área de expansión Belén', 'La Libertad', 'Los Balsos No.2',
       'Picacho', 'Florida Nueva', 'Carlos E. Restrepo', 'Altamira',
       'Versalles No.1', 'Asomadera No.1', 'Calle Nueva', 'Fátima',
       'Villa Flora', 'Campo Amor', 'La Alpujarra', 'Oleoducto',
       'Santa María de los Ángeles', 'La Colina', 'San Miguel',
       'Pablo VI', 'El Rodeo', 'Universidad Nacional', 'San Joaquín',
       'Mirador del Doce', 'Héctor Abad Gómez',
       'Área de expansión Pajarito', 'Las Acacias', 'Moscú No.1',
       'Centro Administrativo', 'Altavista', 'La Pilarica', 'Tejelo',
       'Las Granjas', 'Cucaracho', 'Popular', 'La Loma',
       'Corazón de Jesús', 'Los Ángeles', 'Girardot', 'San Bernardo',
       'San Germán', 'Tenche', 'Villa Hermosa', 'El Danubio',
       'Facultad de Minas U. Nacional', 'Progreso', 'La Salle',
       'Calasanz', 'Buenos Aires', 'Parque Juan Pablo II',
       'Santo Domingo Savio No.2', 'Juan XXIIIi la Quiebra', 'El Rincón',
       'Alejandro Echavarría', 'El Raizal',
       'Área Urbana Cgto. San Cristóbal', 'Veinte de Julio', 'El Pomar',
       'La América', 'Cementerio Universal', 'Manrique Oriental',
       'Santa Elena sector central', 'El Nogal-Los Almendros',
       'Francisco Antonio Zea', 'La Pradera', 'Santa Lucía',
       'Alfonso López', 'La Esperanza', 'La Mansión', 'Los Balsos No.1',
       'Las Lomas No.2', 'Berlin', 'B. Cerro el Volador', 'Los Colores',
       'Campo Alegre', 'Santa Inés', 'Miravalle', 'La Frontera',
       'Santa Mónica', 'Jardín Botánico', 'Granizal', 'Cuarta Brigada',
       'Nueva Villa del Aburrá', 'Santa Teresita', 'Sucre', 'Las Brisas',
       'Palermo', 'Sin dato', 'Boqueron', 'Bello Horizonte', 'Toscana',
       'Villa Guadalupe', 'Santa Cruz', 'Ferrini', 'Los Pinos',
       'Antonio Nariño', 'La Piñuela', 'La Ladera', 'Diego Echavarría',
       'Castropol', 'Santa Margarita', 'Enciso', 'Los Mangos',
       'Las Mercedes', 'Las Palmas', 'Barrio Cristóbal', 'Bomboná No.2',
       'Belencito', 'Moravia', 'Belalcázar', 'Las Estancias',
       'Playón de los Comuneros', 'U.P.B', 'San Isidro',
       'Bosques de San Pablo', 'Asomadera No.2', 'San José la Cima No.2',
       'Ocho de Marzo', 'San Antonio', 'Villatina', 'La Rosa',
       'Santander', 'Andalucía', 'San Pablo', 'El Corazon el Morro',
       'El Plan', 'Villa del Socorro', 'La Isla', 'Calasania Parte Alta',
       'Barrios de Jesús', 'Altos del Poblado',
       'Hospital San Vicente de Paúl', 'Fuente Clara',
       'Santo Domingo Savio No.1', 'Pedregal Alto', 'La Avanzada',
       'Blanquizal', 'Las Esmeraldas', 'Nueva Villa de la Iguaná',
       'María Cano-Carambolas', 'Olaya Herrera', 'La Hondonada',
       'Juan Pablo II', 'El Castillo', 'Área de expansión Altavista',
       'El Diamante No.2', 'Batallón Girardot',
       'Área de expansión San Antonio De Prado', 'Las Independencias',
       'Moscú No.2', 'Aldea Pablo VI', 'Llanaditas', 'Picachito',
       'Progreso No.2', 'El Socorro', 'Villa Niza',
       'Nuevos Conquistadores', 'San Jose', 'Monteclaro',
       'Área de expansión Calasanz', 'La Verde', 'Carpinelo',
       'Fac. Veterinaria y Zootecnia U.De.A.', 'Metropolitano',
       'Eduardo Santos', 'La Cuchilla', 'Villa Lilliam',
       'La Esperanza No.2', 'San Jose del Manzanillo',
       'San José la Cima No.1', 'Potrerito', 'Trece de Noviembre',
       'Piedras Blancas Matasano', 'Montanita', 'Mazo', 'El Pesebre',
       'El Llano Santa Elena', 'El Salado', 'El Picacho', 'La Cruz',
       'Betania', 'Travesias', 'Santa Rosa de Lima', 'La Sierra',
       'El Yolombo', 'El Jardin', 'El Carmelo', 'El Placer', 'Oriente',
       'Altavista Sector Central', 'El Compromiso',
       'Sin dato 80 San Antonio de Prado', 'El Llano',
       'Sin dato 90 Santa Elena', 'El Cerro', 'Villa Turbay',
       'Versalles No.2', 'Yarumalito', 'Barro Blanco', 'Aguas Frias',
       'Sin dato 10 La Candelaria', 'El Triunfo', 'Asomadera No.3',
       'El Astillero', 'El Uvito', 'San Jose de La Montaña', 'La Ilusion',
       'Palmitas sector central', 'V. El Salado', 'La Aldea',
       'La Frisola', 'Sin dato 60 San Cristobal', 'Buga Patio Bonito',
       'La Sucia', 'El Patio', 'Potrera Miserenga', 'Urquita', 'La Suiza',
       'Área de expansión Eduardo Santos', 'Área de expansión El Noral',
       'Sin dato 9 Buenos Aires', 'Sin dato 16 Belen',
       'Sin dato 13 San Javier', 'Sin dato 14 El Poblado',
       'Sin dato 3 Manrique', 'Sin dato 7 Robledo',
       'Sin dato 15 Guayabal', 'Sin dato 6 Doce de Octubre',
       'Sin dato 11 Laureles -  Estadio'], dtype=object)

In [ ]:
# Cambiar el tipo de datos en algunas columnas del dataset

## Cambiar tipo de dato de algunos campos
df_hurtos_MDE = df_hurtos_MDE.astype({'edad': 'uint8',
                                           'cantidad':'uint8',
                                          'estado_civil':'category',
                                          'sexo':'category',
                                          'bien':'category',
                                  'actividad_delictiva':'category',
                                  'sede_receptora':'category',
                                  'color':'category',
                                  'modalidad':'category'
                           })
df_hurtos_MDE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326489 entries, 0 to 326488
Data columns (total 33 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   fecha_hecho          326489 non-null  object
 1   cantidad             326489 non-null  uint8
 2   sexo                 326489 non-null  category
 3   edad                 326489 non-null  uint8
 4   estado_civil         326489 non-null  category
 5   grupo_actor          326489 non-null  object
 6   actividad_delictiva  326489 non-null  category
 7   parentesco           326489 non-null  object
 8   ocupacion            326489 non-null  object
 9   discapacidad         326489 non-null  object
 10  grupo_especial       326489 non-null  object
 11  medio_transporte     326489 non-null  object
 12  nivel_academico      326489 non-null  object
 13  testigo              326489 non-null  object
 14  conducta             326489 non-null  object
 15  modalidad            326489 non-null  category
 16  caracterizacion      326489 non-null  object
 17  conducta_especial    326489 non-null  object
 18  arma_medio           326489 non-null  object
 19  articulo_penal       326489 non-null  object
 20  categoria_penal      326489 non-null  object
 21  nombre_barrio        326489 non-null  object
 22  codigo_barrio        326489 non-null  object
 23  codigo_comuna        326489 non-null  object
 24  lugar                326489 non-null  object
 25  sede_receptora       326489 non-null  category
 26  bien                 326489 non-null  category
 27  categoria_bien       326489 non-null  object
 28  grupo_bien           326489 non-null  object
 29  color                326489 non-null  category
 30  permiso              326489 non-null  object
 31  unidad_medida        326489 non-null  object
 32  fecha_ingestion      326489 non-null  object
dtypes: category(7), object(24), uint8(2)
memory usage: 62.9+ MB

In [ ]:
# Creamos una copia del df original
df_hurtos_MDE_Limp=df_hurtos_MDE

In [ ]:
# Agrupamos por sexo y almacenamos el resultado en un variable
df_hurtos_MDE_sexo=df_hurtos_MDE_Limp.groupby('sexo').size()
df_hurtos_MDE_sexo

/tmp/ipykernel_4279/1343840288.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_hurtos_MDE_sexo=df_hurtos_MDE_Limp.groupby('sexo').size()

sexo
Hombre      191368
Mujer       133420
Sin dato      1701
dtype: int64

In [ ]:
# Tratar los valores atipicos en edad
df_hurtos_MDE_Limp.edad.replace({
                           -1: None,
                           121:None,
                           255:None}, inplace =True)

In [ ]:
# Verificamos nuevamente los campos de edad
pd.unique(df_hurtos_MDE_Limp['edad'])

array([33, 26, 30, 37, 87, 29, 27, 36, 41, 59, 39, 38, 43, 22, 20, 64, 35,
       18, 28, 40, 32, 45, 23, 17, 19, 31, 34, 25, 51, 49, 21, 47, 56, 55,
       46, 48, 66, 52, 16, 54, 24, 65, 53, 42, 44, 60, 6, 50, 62, 15, 69,
       61, 77, 63, 73, 58, 76, 14, None, 70, 57, 81, 71, 72, 67, 13, 84,
       68, 88, 74, 75, 90, 8, 78, 80, 10, 85, 79, 11, 7, 89, 86, 2, 83,
       82, 93, 9, 12, 91, 1, 92, 94, 96, 4, 95, 3, 5], dtype=object)

In [ ]:
# Identificamos cantidades por   edad
df_hurtos_MDE_edad= df_hurtos_MDE_Limp.groupby('edad').size().sort_values(ascending=True)
df_hurtos_MDE_edad

edad
95        1
93        3
94        4
5         5
96        7
      ...
26    11980
28    11991
27    12276
25    12361
35    12951
Length: 96, dtype: int64

In [ ]:
# Identificamos las cantiades por barrio
df_hurtos_MDE_barrio=df_hurtos_MDE_Limp.groupby('nombre_barrio').size().sort_values(ascending=False)
df_hurtos_MDE_barrio

nombre_barrio
La Candelaria                       37473
El Poblado                           9479
Guayaquil                            6945
Barrio Colón                         6654
Estadio                              6011
                                    ...
Potrera Miserenga                       3
La Suiza                                1
Sin dato 11 Laureles -  Estadio         1
Área de expansión El Noral              1
Área de expansión Eduardo Santos        1
Length: 332, dtype: int64

In [ ]:
# Identificamos cantidades por bien
df_hurtos_MDE_bien= df_hurtos_MDE_Limp.groupby('bien').size().sort_values(ascending=False)
df_hurtos_MDE_bien

/tmp/ipykernel_4279/2708959548.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_hurtos_MDE_bien= df_hurtos_MDE_Limp.groupby('bien').size().sort_values(ascending=False)

bien
Celular                         94490
Peso                            60195
Sin dato                        30458
Accesorios prendas de vestir    21072
Cédula                          16257
                                ...
Ametralladora                       1
Toma                                1
Tortuga                             1
Vainilla                            1
Ácido                               1
Length: 441, dtype: int64

In [ ]:
# Identificamos por estado civil
df_hurtos_MDE_estado_civil=df_hurtos_MDE_Limp.groupby('estado_civil').size().sort_values(ascending=False)
df_hurtos_MDE_estado_civil

/tmp/ipykernel_4279/2306341731.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_hurtos_MDE_estado_civil=df_hurtos_MDE_Limp.groupby('estado_civil').size().sort_values(ascending=False)

estado_civil
Soltero(a)                172327
Casado(a)                  59263
Unión marital de hecho     44729
Sin dato                   38103
Divorciado(a)               8842
Viudo(a)                    3225
dtype: int64

In [ ]:
# Agrupar por varios campos
hurtos_barrio_sexo=df_hurtos_MDE_Limp.groupby(['sexo', 'nombre_barrio']).size().sort_values(ascending=False)
hurtos_barrio_sexo

/tmp/ipykernel_4279/4254153655.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  hurtos_barrio_sexo=df_hurtos_MDE_Limp.groupby(['sexo', 'nombre_barrio']).size().sort_values(ascending=False)

sexo      nombre_barrio
Hombre    La Candelaria                             19921
Mujer     La Candelaria                             17416
Hombre    El Poblado                                 5691
Mujer     El Poblado                                 3685
Hombre    Estadio                                    3629
                                                    ...
Sin dato  San Lucas                                     0
          San José la Cima No.2                         0
          Área de expansión Eduardo Santos              0
          Área de expansión El Noral                    0
          Área de expansión San Antonio De Prado        0
Length: 996, dtype: int64

In [ ]:
hurtos_edad_sexo=df_hurtos_MDE_Limp.groupby(['sexo', 'edad']).size().sort_values(ascending=False)
hurtos_edad_sexo

/tmp/ipykernel_4279/3424296032.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  hurtos_edad_sexo=df_hurtos_MDE_Limp.groupby(['sexo', 'edad']).size().sort_values(ascending=False)

sexo      edad
Hombre    35      7843
          28      7325
          25      7239
          27      7232
          26      7159
                  ...
Sin dato  76         0
          77         0
          78         0
          79         0
          80         0
Length: 288, dtype: int64

In [ ]:
df_hurtos_MDE_bien=df_hurtos_MDE_Limp.groupby(['sexo', 'nombre_barrio', 'bien']).size().sort_values(ascending=False)
df_hurtos_MDE_bien

/tmp/ipykernel_4279/1843906164.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_hurtos_MDE_bien=df_hurtos_MDE_Limp.groupby(['sexo', 'nombre_barrio', 'bien']).size().sort_values(ascending=False)

sexo    nombre_barrio   bien
Hombre  La Candelaria   Celular     6857
Mujer   La Candelaria   Celular     5661
Hombre  La Candelaria   Peso        4225
Mujer   La Candelaria   Peso        3321
Hombre  Sin dato        Sin dato    2543
                                    ...
Mujer   Barrio Caycedo  Casa           0
                        Carátula       0
                        Cartón         0
                        Cartucho       0
                        Champaña       0
Length: 439236, dtype: int64

In [ ]:
pd.unique(df_hurtos_MDE_Limp.modalidad)

['Atraco', 'Descuido', 'Engaño', 'Rompimiento de ventana', 'Sin dato', ..., 'Retención de dinero', 'Auto robo', 'Llamada millonaria', 'Fleteo', 'Rompimiento cerradura']
Length: 30
Categories (30, object): ['Abuso de confianza', 'Atraco', 'Auto robo', 'Clonación de tarjeta', ...,
                          'Suplantación', 'Tóxico o agente químico', 'Vandalismo',
                          'Violencia intrafamiliar']

In [ ]:
df_hurtos_MDE_Limp.modalidad.replace({"Rompimiento cerraduta": "Rompimiento cerradura"},
                    inplace=True)

/tmp/ipykernel_4279/2681342435.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_hurtos_MDE_Limp.modalidad.replace({"Rompimiento cerraduta": "Rompimiento cerradura"},

In [ ]:
hurtos_modalidad=df_hurtos_MDE_Limp.groupby(['modalidad']).size().sort_values(ascending=False)
hurtos_modalidad

/tmp/ipykernel_4279/83823044.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  hurtos_modalidad=df_hurtos_MDE_Limp.groupby(['modalidad']).size().sort_values(ascending=False)

modalidad
Atraco                                  163052
Descuido                                 60264
Cosquilleo                               39171
Raponazo                                 21887
Sin dato                                 11294
Rompimiento cerradura                     7332
Engaño                                    6984
Escopolamina                              4434
Rompimiento de ventana                    4252
Halado                                    3117
Clonación de tarjeta                       933
Comisión de delito                         665
Suplantación                               640
Paquete chileno                            390
Abuso de confianza                         338
Informático                                333
Llave maestra                              323
Fleteo                                     319
Miedo o terror                             245
Simulando necesidad                        153
Retención de tarjeta                       135
Llamada millonaria                         107
Forcejeo                                    62
Retención de dinero                         37
Tóxico o agente químico                     10
Enfrentamiento con la fuerza pública         5
Auto robo                                    4
Violencia intrafamiliar                      2
Vandalismo                                   1
dtype: int64

In [ ]:
hurtos_modalidad_sexo= df_hurtos_MDE_Limp.groupby(['sexo', 'modalidad']).size().sort_values(ascending=False)
hurtos_modalidad_sexo

/tmp/ipykernel_4279/1400866007.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  hurtos_modalidad_sexo= df_hurtos_MDE_Limp.groupby(['sexo', 'modalidad']).size().sort_values(ascending=False)

sexo      modalidad
Hombre    Atraco                     106354
Mujer     Atraco                      55775
Hombre    Descuido                    34188
Mujer     Descuido                    25869
          Cosquilleo                  22113
                                      ...
Sin dato  Llamada millonaria              0
          Simulando necesidad             0
          Tóxico o agente químico         0
          Vandalismo                      0
          Violencia intrafamiliar         0
Length: 87, dtype: int64

In [ ]:
hurtos_modalidad_sexo_edad=df_hurtos_MDE_Limp.groupby(['sexo', 'edad', 'modalidad']).size().sort_values(ascending=False)
hurtos_modalidad_sexo_edad

/tmp/ipykernel_4279/1003768377.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  hurtos_modalidad_sexo_edad=df_hurtos_MDE_Limp.groupby(['sexo', 'edad', 'modalidad']).size().sort_values(ascending=False)

sexo    edad  modalidad
Hombre  35    Atraco                     4391
        25    Atraco                     4355
        27    Atraco                     4319
        26    Atraco                     4263
        28    Atraco                     4249
                                         ...
Mujer   20    Tóxico o agente químico       0
              Suplantación                  0
              Retención de tarjeta          0
              Miedo o terror                0
        21    Miedo o terror                0
Length: 8352, dtype: int64