# **Limpieza y Transformacion de los datos**

El proceso de preprocesamiento de datos se lleva a cabo una vez que hemos explorado y limpiado nuestro conjunto de datos, de modo que entendamos su contenido, estructura y calidad. Al explorar nuestros datos, es probable que obtengamos una buena idea de como queremos modelarlos, lo cual nos ayudara a decidir de mejor manera de preprocesarlos para que esten listos para el modelado desde el principio.

In [ ]:
# Importamos pandas
import pandas as pd

# Cargamos el dataset
df= pd.read_csv('/content/drive/MyDrive/Dataset G659 UDEA/clientes.csv', sep=',')

# Imprimimos la data
df

,ID del cliente,Nombre,Última fecha de compra,Frecuencia de compra,Valor promedio de la compra,Categoría de productos comprados,Método de pago,Edad
0,1,Juan Perez,15/03/2022,5,200.5,Ropa,Tarjeta de crédito,32.0
1,2,Ana Rodriguez,01/04/2022,2,80.0,Juguetes,Efectivo,45.0
2,3,Luisa Hernandez,10/12/2021,3,150.2,Electrónica,Transferencia bancaria,28.0
3,4,Carlos Garcia,28/02/2022,1,300.0,Alimentos,Tarjeta de crédito,50.0
4,5,Maria Gomez,20/03/2022,4,75.8,Ropa,Efectivo,22.0
...,...,...,...,...,...,...,...,...
152,160,Andrea Soto,09/06/2022,2,50.0,Electrónica,Transferencia bancaria,25.0
153,161,Laura Hernandez,06/06/2022,1,120.0,Alimentos,Efectivo,39.0
154,145,Luis Garcia,04/06/2022,4,75.2,Alimentos,Transferencia bancaria,28.0
155,154,Luisa Perez,08/06/2022,2,80.0,Ropa,Transferencia bancaria,33.0
156,160,Andrea Soto,09/06/2022,2,50.0,Electrónica,Transferencia bancaria,25.0

In [ ]:
# Mostramos lso primeros 5 registros
df.head()

,ID del cliente,Nombre,Última fecha de compra,Frecuencia de compra,Valor promedio de la compra,Categoría de productos comprados,Método de pago,Edad
0,1,Juan Perez,15/03/2022,5,200.5,Ropa,Tarjeta de crédito,32.0
1,2,Ana Rodriguez,01/04/2022,2,80.0,Juguetes,Efectivo,45.0
2,3,Luisa Hernandez,10/12/2021,3,150.2,Electrónica,Transferencia bancaria,28.0
3,4,Carlos Garcia,28/02/2022,1,300.0,Alimentos,Tarjeta de crédito,50.0
4,5,Maria Gomez,20/03/2022,4,75.8,Ropa,Efectivo,22.0

In [ ]:
# Mostrar los ultimos 5 registros
df.tail()

,ID del cliente,Nombre,Última fecha de compra,Frecuencia de compra,Valor promedio de la compra,Categoría de productos comprados,Método de pago,Edad
152,160,Andrea Soto,09/06/2022,2,50.0,Electrónica,Transferencia bancaria,25.0
153,161,Laura Hernandez,06/06/2022,1,120.0,Alimentos,Efectivo,39.0
154,145,Luis Garcia,04/06/2022,4,75.2,Alimentos,Transferencia bancaria,28.0
155,154,Luisa Perez,08/06/2022,2,80.0,Ropa,Transferencia bancaria,33.0
156,160,Andrea Soto,09/06/2022,2,50.0,Electrónica,Transferencia bancaria,25.0

In [ ]:
# Mostramos la informacion tecnica de las columnas
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID del cliente                    157 non-null    int64
 1   Nombre                            155 non-null    object
 2   Última fecha de compra            156 non-null    object
 3   Frecuencia de compra              157 non-null    int64
 4   Valor promedio de la compra       152 non-null    float64
 5   Categoría de productos comprados  151 non-null    object
 6   Método de pago                    153 non-null    object
 7   Edad                              154 non-null    float64
dtypes: float64(2), int64(2), object(4)
memory usage: 9.9+ KB

In [ ]:
# Mostrar informacion estadistica de la data
df.describe()

,ID del cliente,Frecuencia de compra,Valor promedio de la compra,Edad
count,157.000000,157.000000,152.00000,154.000000
mean,82.579618,2.369427,118.23750,31.233766
std,47.555248,1.172804,249.86509,9.146443
min,1.000000,1.000000,20.00000,1.000000
25%,42.000000,1.000000,65.20000,26.000000
50%,83.000000,2.000000,85.10000,30.000000
75%,124.000000,3.000000,120.28750,37.000000
max,161.000000,5.000000,3110.00000,80.000000

In [ ]:
# Obtener la cantidad de datos nulos por columna
df.isnull().sum()

ID del cliente                      0
Nombre                              2
Última fecha de compra              1
Frecuencia de compra                0
Valor promedio de la compra         5
Categoría de productos comprados    6
Método de pago                      4
Edad                                3
dtype: int64

In [ ]:
# Filtramos las filas donde la columna 'Edad tiene valores nulos
df[df['Edad'].isnull()]

,ID del cliente,Nombre,Última fecha de compra,Frecuencia de compra,Valor promedio de la compra,Categoría de productos comprados,Método de pago,Edad
52,55,Carlos Moreno,14/03/2022,1,210.0,Juguetes,Tarjeta de crédito,NaN
84,89,David Torres,23/03/2022,3,75.6,Alimentos,Transferencia bancaria,NaN
107,114,Maria Sanchez,11/05/2022,1,110.0,Ropa,NaN,NaN

In [ ]:
# Eliminamos las filas con indices
df=df.drop([52,84,107])

In [ ]:
# Verificamos si aun existen registros de la columna edad
df[df['Edad'].isnull()]

Empty DataFrame
Columns: [ID del cliente, Nombre, Última fecha de compra, Frecuencia de compra, Valor promedio de la compra, Categoría de productos comprados, Método de pago, Edad]
Index: []

In [ ]:
# Filtramos las filas donde la columna 'Nombre' tiene valores nulos
df[df['Nombre'].isnull()]

,ID del cliente,Nombre,Última fecha de compra,Frecuencia de compra,Valor promedio de la compra,Categoría de productos comprados,Método de pago,Edad
142,150,NaN,06/06/2022,1,100.0,Ropa,NaN,28.0
149,157,NaN,01/06/2022,2,35.5,Alimentos,Transferencia bancaria,38.0

In [ ]:
# Eliminamos los registros de la columna nombre
df = df.drop([142,149])

In [ ]:
# Verificamos nuevamente si hay valores nulos con nombre
df[df['Nombre'].isnull()]

Empty DataFrame
Columns: [ID del cliente, Nombre, Última fecha de compra, Frecuencia de compra, Valor promedio de la compra, Categoría de productos comprados, Método de pago, Edad]
Index: []

In [ ]:
# Verificar si hay valores nulos con la ultima fecha de compra
df[df['Última fecha de compra'].isnull()]

,ID del cliente,Nombre,Última fecha de compra,Frecuencia de compra,Valor promedio de la compra,Categoría de productos comprados,Método de pago,Edad
30,32,Andrea Torres,NaN,3,120.5,NaN,Tarjeta de crédito,26.0

In [ ]:
# Eliminar registros de ultima fecha de compra
df=df.drop([30])

In [ ]:
# Verificamos nuevamente los valores nulos de Ultima fecha de compra
df[df['Última fecha de compra'].isnull()]

Empty DataFrame
Columns: [ID del cliente, Nombre, Última fecha de compra, Frecuencia de compra, Valor promedio de la compra, Categoría de productos comprados, Método de pago, Edad]
Index: []

In [ ]:
# Verficar valor promedio de la compra
df[df['Valor promedio de la compra'].isnull()]

,ID del cliente,Nombre,Última fecha de compra,Frecuencia de compra,Valor promedio de la compra,Categoría de productos comprados,Método de pago,Edad
16,18,Jorge Martinez,14/03/2022,4,NaN,NaN,NaN,39.0
35,38,Ana Garcia,15/04/2022,2,NaN,Ropa,Transferencia bancaria,27.0
43,46,Oscar Perez,11/04/2022,5,NaN,Ropa,Efectivo,23.0
67,71,Ana Flores,29/04/2022,4,NaN,Juguetes,Transferencia bancaria,33.0
117,124,Karen Martinez,01/05/2022,3,NaN,NaN,Transferencia bancaria,33.0

In [ ]:
# Eliminamos los valores nulos de la compra
df=df.drop([16,35,43,67,117])

In [ ]:
# Verificamos nuevamente
df[df['Valor promedio de la compra'].isnull()]

Empty DataFrame
Columns: [ID del cliente, Nombre, Última fecha de compra, Frecuencia de compra, Valor promedio de la compra, Categoría de productos comprados, Método de pago, Edad]
Index: []

In [ ]:
# Verificamos categoria productos comprados
df[df['Categoría de productos comprados'].isnull()]

,ID del cliente,Nombre,Última fecha de compra,Frecuencia de compra,Valor promedio de la compra,Categoría de productos comprados,Método de pago,Edad
49,52,Andrea Garcia,18/04/2022,4,120.25,NaN,Tarjeta de crédito,28.0
58,61,Ricardo Torres,23/02/2022,3,40.20,NaN,Efectivo,19.0
70,74,Luis Martinez,04/05/2022,2,70.00,NaN,Tarjeta de crédito,25.0

In [ ]:
# Eliminamos los valores nulos de la categoria de productos
df=df.drop([49,58,70])

In [ ]:
# Verficamos nuevamenete los valores nulos en categoria de productos
df[df['Categoría de productos comprados'].isnull()]

Empty DataFrame
Columns: [ID del cliente, Nombre, Última fecha de compra, Frecuencia de compra, Valor promedio de la compra, Categoría de productos comprados, Método de pago, Edad]
Index: []

In [ ]:
# Verificamos nuevamente si hay valores nulos
df[df['Método de pago'].isnull()]

,ID del cliente,Nombre,Última fecha de compra,Frecuencia de compra,Valor promedio de la compra,Categoría de productos comprados,Método de pago,Edad
83,88,Ana Mendoza,08/05/2022,2,55.7,Electrónica,NaN,22.0

In [ ]:
# Eliminamos los valores nulos de metodo de pago
df=df.drop([83])

In [ ]:
# Verificamos nuevamente si hay valores nulos
df[df['Método de pago'].isnull()]

Empty DataFrame
Columns: [ID del cliente, Nombre, Última fecha de compra, Frecuencia de compra, Valor promedio de la compra, Categoría de productos comprados, Método de pago, Edad]
Index: []

In [ ]:
# Verificamos nuevamente si hay valores nulos por columnas
df.isnull().sum()

ID del cliente                      0
Nombre                              0
Última fecha de compra              0
Frecuencia de compra                0
Valor promedio de la compra         0
Categoría de productos comprados    0
Método de pago                      0
Edad                                0
dtype: int64

In [ ]:
# Verificamos datos atipicos
df[df['Edad']<18]

,ID del cliente,Nombre,Última fecha de compra,Frecuencia de compra,Valor promedio de la compra,Categoría de productos comprados,Método de pago,Edad
36,39,Luis Perez,11/02/2022,1,280.0,Juguetes,Tarjeta de crédito,2.0
72,76,Laura Gutierrez,05/05/2022,3,60.7,Electrónica,Transferencia bancaria,3.0
147,155,Daniel Ortiz,07/06/2022,1,90.0,Juguetes,Efectivo,1.0

In [ ]:
# Eliminar valores atipicos
df=df.drop(df[df['Edad']<18].index)

In [ ]:
# Verificamos nevamente si hay datos atipicos
df[df['Edad']<18]

Empty DataFrame
Columns: [ID del cliente, Nombre, Última fecha de compra, Frecuencia de compra, Valor promedio de la compra, Categoría de productos comprados, Método de pago, Edad]
Index: []

In [ ]:
# Eliminar variables irrelevantes
df=df.drop(['Nombre'], axis=1)
df

KeyError: "['Nombre'] not found in axis"

# **Transformacion de variables**

**Codificacion one-hot:** esta tecnica implica crear una columna binaria para cada categoria de la variable categorica. La columna tendra un valor de 1 si la categoria esta presente y 0 en caso contrario. Pandas tiene una funcion get_dummies que realiza esta codificacion.

In [ ]:
# Transformar la variable de metodo de pago
df=pd.get_dummies(df, columns=['Método de pago'])
df

,ID del cliente,Última fecha de compra,Frecuencia de compra,Valor promedio de la compra,Categoría de productos comprados,Edad,Método de pago_Efectivo,Método de pago_Tarjeta de crédito,Método de pago_Transferencia bancaria
0,1,15/03/2022,5,200.5,Ropa,32.0,False,True,False
1,2,01/04/2022,2,80.0,Juguetes,45.0,True,False,False
2,3,10/12/2021,3,150.2,Electrónica,28.0,False,False,True
3,4,28/02/2022,1,300.0,Alimentos,50.0,False,True,False
4,5,20/03/2022,4,75.8,Ropa,22.0,True,False,False
...,...,...,...,...,...,...,...,...,...
152,160,09/06/2022,2,50.0,Electrónica,25.0,False,False,True
153,161,06/06/2022,1,120.0,Alimentos,39.0,True,False,False
154,145,04/06/2022,4,75.2,Alimentos,28.0,False,False,True
155,154,08/06/2022,2,80.0,Ropa,33.0,False,False,True
156,160,09/06/2022,2,50.0,Electrónica,25.0,False,False,True

**Codificacion ordinal:** esta tecnica implica asignar un numero unico a cada categoria de la variable en orden de importancia o frecuencia

In [ ]:
# Transformar la categoria de productos
df['Categoría de productos comprados']=df['Categoría de productos comprados'].map({'Ropa':1, 'Juguetes':2, 'Electrónica':3, 'Alimentos':4})
df

,ID del cliente,Última fecha de compra,Frecuencia de compra,Valor promedio de la compra,Categoría de productos comprados,Edad,Método de pago_Efectivo,Método de pago_Tarjeta de crédito,Método de pago_Transferencia bancaria
0,1,15/03/2022,5,200.5,1,32.0,False,True,False
1,2,01/04/2022,2,80.0,2,45.0,True,False,False
2,3,10/12/2021,3,150.2,3,28.0,False,False,True
3,4,28/02/2022,1,300.0,4,50.0,False,True,False
4,5,20/03/2022,4,75.8,1,22.0,True,False,False
...,...,...,...,...,...,...,...,...,...
152,160,09/06/2022,2,50.0,3,25.0,False,False,True
153,161,06/06/2022,1,120.0,4,39.0,True,False,False
154,145,04/06/2022,4,75.2,4,28.0,False,False,True
155,154,08/06/2022,2,80.0,1,33.0,False,False,True
156,160,09/06/2022,2,50.0,3,25.0,False,False,True

In [ ]:
# Renombrar las columnas
df.columns=['Id_cliente', 'Ultima_fecha_compra', 'Frecuencia_compra','Valor_promedio_compra','Categoria_compra', 'Edad', 'Pago_efectivo','Pago_credito','Pago_transferencia']
df

,Id_cliente,Ultima_fecha_compra,Frecuencia_compra,Valor_promedio_compra,Categoria_compra,Edad,Pago_efectivo,Pago_credito,Pago_transferencia
0,1,15/03/2022,5,200.5,1,32.0,False,True,False
1,2,01/04/2022,2,80.0,2,45.0,True,False,False
2,3,10/12/2021,3,150.2,3,28.0,False,False,True
3,4,28/02/2022,1,300.0,4,50.0,False,True,False
4,5,20/03/2022,4,75.8,1,22.0,True,False,False
...,...,...,...,...,...,...,...,...,...
152,160,09/06/2022,2,50.0,3,25.0,False,False,True
153,161,06/06/2022,1,120.0,4,39.0,True,False,False
154,145,04/06/2022,4,75.2,4,28.0,False,False,True
155,154,08/06/2022,2,80.0,1,33.0,False,False,True
156,160,09/06/2022,2,50.0,3,25.0,False,False,True

In [ ]:
df.to_csv('clientes_limpios.csv', index=False)